[안남규,송재관] : models.py 생성
wecode-bootcamp-korea/32-2nd-weClass200-backend pull request #1
Opened 2022-05-10 06:41 UTC by NamkyuAhn

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- models.py 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
erd의 테이블들을 총 두개의 앱으로 나누어 models.py 생성함
users app에는 users, creators, myclasses, reviews 테이블이 있으며, products app에는 maincategories, subcategories, products, products_images 테이블이 있음

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-10 09:27 UTC, lordmyshepherd requested changes

2022-05-10 09:27 UTC, lordmyshepherd commented on products/models.py
> +        db_table = 'maincategories'
table 명은 snake_case로 만들어주세요~
```suggestion
        db_table = 'main_categories'
```

2022-05-10 09:27 UTC, lordmyshepherd commented on products/models.py
> +        db_table = 'subcategories'
마찬가지 입니다!!

2022-05-10 09:27 UTC, lordmyshepherd commented on products/models.py
> +    review_score    = models.DecimalField(max_digits=2, decimal_places=1)
review_score는 별도로 저장하지 않기로 했지 않나요?

2022-05-10 09:27 UTC, lordmyshepherd commented on products/models.py
> +    review_score    = models.DecimalField(max_digits=2, decimal_places=1)
review 테이블에 있는 score로 충분히 계산할 수 있을 것 같습니다.

2022-05-10 09:27 UTC, lordmyshepherd commented on products/models.py
> +    url5    = models.CharField(max_length=500, null=True)
왜 url이 5개나 필요한가요?

컬럼이 아니라 행(row)가 5개 생성되면 되지 않을까요?

```suggestion
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='images')
    url1    = models.CharField(max_length=500, null=True)
    url2    = models.CharField(max_length=500, null=True)
    url3    = models.CharField(max_length=500, null=True)
    url4    = models.CharField(max_length=500, null=True)
    url5    = models.CharField(max_length=500, null=True)
```

2022-05-10 09:27 UTC, lordmyshepherd commented on users/models.py
> +        db_table = 'creators'
처음부터 Creator로만 등록할 수 있나요?
처음에는 일반 유저 상태에서 Creator로 등록하는게 기획 아닌가요?

기존 유저가 Creator로 전환되는 기획이라면 아래와 같이 수정되야 될 것 같습니다.

```suggestion
class Creator(models.Model):
    user = models.ForeignKey('Users')
    email         = models.CharField(max_length=200)
    phone_number  = models.CharField(max_length=50, null=True)
    profile_image = models.CharField(max_length=500)
    introduction  = models.CharField(max_length=1000)
    carrer        = models.CharField(max_length=1000)

    class Meta:
        db_table = 'creators'
```

2022-05-10 09:27 UTC, lordmyshepherd commented on users/models.py
> +    url5    = models.CharField(max_length=500, null=True)
여기도 url 컬럼이 왜 5개나 필요한가요?
```suggestion
class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.SET_NULL, null=True)
    url1    = models.CharField(max_length=500, null=True)
    url2    = models.CharField(max_length=500, null=True)
    url3    = models.CharField(max_length=500, null=True)
    url4    = models.CharField(max_length=500, null=True)
    url5    = models.CharField(max_length=500, null=True)
```

2022-05-10 09:38 UTC, NamkyuAhn commented on products/models.py
> +    review_score    = models.DecimalField(max_digits=2, decimal_places=1)
따로 분리하는 방안에서 다시 products 테이블 안의 컬럼으로 추가하기로 했습니다.

2022-05-10 09:46 UTC, NamkyuAhn commented on users/models.py
> +        db_table = 'creators'
nickname은 유저의 이름과 강의할때의 필명이 다른 경우가 있을 수 있어서 필요한 필드입니다. 조언 감사합니다!

2022-05-10 09:47 UTC, NamkyuAhn commented on products/models.py
> +    review_score    = models.DecimalField(max_digits=2, decimal_places=1)
리뷰를 등록할 때 마다 평균값을 review_score에 업데이트 하려고 했습니다.

2022-05-11 01:50 UTC, Kang-kyunghun requested changes

2022-05-11 01:50 UTC, Kang-kyunghun commented on users/models.py
> +    image_urls = models.TextField()
url을 지정하는데 TextField는 너무 과도하게 설정 한 것 같습니다. CharField로 적당한 max_length를 지정해 주세요.(이 부분뿐만 아니라 url 관련해서 TextField로 지정한 부분은 전부 수정해 주세요.)

2022-05-11 02:26 UTC, NamkyuAhn commented on users/models.py
> +    image_urls = models.TextField()
s3의 파일 주소 길이가 얼마나 될지 몰라서 textfield로 해봤습니다. 수정했습니다!!

2022-05-11 05:46 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-05-11 05:46 UTC, merged