[안남규] : view 추가
wecode-bootcamp-korea/32-2nd-weClass200-backend pull request #7
Opened 2022-05-16 11:52 UTC by NamkyuAhn

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)
products : nav바 view, main페이지 view, 상세페이지 view, 상품 리스트 view 추가
users : 리뷰 작성하는 api 추가
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
ReviewView : json으로 받아온 데이터들을 reviews, review_images 테이블에 삽입하고, 해당 리뷰가 달린 product의 review_score 점수반영

추가 구현중 : 카테고리별 분류, 정렬 옵션(가격순, 신상품순 등)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 재관님의 kakao_view 브랜치를 머지하여 작업했는데 rebase가 꼬입니다

2022-05-18 05:47 UTC, lordmyshepherd commented on users/views.py
> +class ReviewView(View):
```python
class ReviewView(View):
    @login_decorator
    def post(self, request):
        # client file data 통신 여부 확인 필요.
        # file data 전송시 boto3 SDK 사용해서 AWS S3에 파일 업로드 기능 구현 필요.
        data       = json.loads(request.body)
        score      = data['rating']
        user_id    = request.user.id
        product_id = data['product_id']
        detail     = data['content']
        image_url  = data['image_url']

        # line 58~86 코드 update_or_create 사용해서 리펙토링 필요
        if Review.objects.filter(product_id = product_id, user_id = user_id).exists():
            Review.objects.filter(product_id = product_id, user_id = user_id).update(
                user_id = user_id,
                product_id = product_id,
                score = score,
                detail = detail
            )

            review_id = Review.objects.filter(user_id = user_id, product_id = product_id)[0].id

            ReviewImage.objects.update(
                review_id = review_id,
                image_urls = image_url
            )
            
        else :
            Review.objects.filter(product_id = product_id, user_id = user_id).create(
                user_id = user_id,
                product_id = product_id,
                score = score,
                detail = detail
            )

            review_id = Review.objects.filter(user_id = user_id, product_id = product_id)[0].id

            ReviewImage.objects.create(
                review_id = review_id,
                image_urls = image_url
            )
        
        # product.review_score 컬럼에 매번 값을 계산해서 저장할 필요가 없을 것 같습니다.
        # 결록적으로 line 90~93 코드는 필요 없을 것 같습니다.
        product = Product.objects.get(id = product_id)
        reviews = Review.objects.filter(product_id = product.id)
        product.reveiw_score = ((product.review_score + score)/reviews.count())

        return JsonResponse({'message' : 'created'}, status = 201)

    @login_decorator
    def delete(self, request, review_id):
        # transaction 적용 필요
        review = Review.objects.get(id=review_id, user_id = request.user.id)
        review.images.all().delete()
        review.delete()
        
        return HttpResponse(status = 204)


```

2022-05-18 05:47 UTC, lordmyshepherd commented on users/views.py
> +class MyClassView(View):
```python
class MyClassListView(View):
    @login_decorator
    def get(self, request):
        # 리턴 값 수정 필요
        user_id  = request.user.id
        my_class = MyClass.objects.filter(user_id = user_id)

        result = []

        for product in my_class:
            result.append({
                "id"              : product.id,
                "content_name"    : product.name,
                "creator_name"    : product.creator.nickname,
                "thumb_img"       : product.images.all()[0].image_urls,
                "price_amount"    : int(product.price),
                "discount_rate"   : product.discount_rate,
                "discount_coupon" : product.discount_coupon,
                "month"           : product.period,
            })

        return JsonResponse({'myclass_result' : result}, status=200)

```

2022-05-18 05:47 UTC, lordmyshepherd commented on users/views.py
> +class LikeView(View):
```python
class LikeView(View):
    @login_decorator
    def post(self,request):
        data = json.loads(request.body)
        product_id = data['product_id']
        user_id    = request.user.id

        if Like.objects.filter(product_id = product_id, user_id = user_id).exists():
            Like.objects.filter(product_id = product_id, user_id = user_id).delete()

            return HttpResponse(status = 204)

        Like.objects.create(user_id = user_id, product_id = product_id)

        return JsonResponse({'message' : 'liked'}, status=201)

    @login_decorator
    def get(self, request):
        data       = json.loads(request.body)
        product_id = data['product_id']
        user_id    = request.user.id
        likes      = Like.objects.filter(user_id = user_id, product_id = product_id) \
            .select_related('product', 'product__creator').prefetch_related('product__images')

        result     = []

        for like in likes:
            result.append({
                "id" : like.product.id,
                "content_name" : like.product.name,
                "creator_name" : like.product.creator.nickname,
                "thumb_img"    : like.product.images.all()[0].image_urls,
                "month" : like.product.period,
            })

        return JsonResponse({'liked_products' : result}, status = 200)

```

2022-05-18 05:47 UTC, lordmyshepherd commented on users/views.py
> +from django.conf     import settings
```python
# built-in modules
import json
import jwt, requests

# 3rd-party modules
from django.views    import View
from django.http     import JsonResponse, HttpResponse
from django.conf     import settings

# custom moduels
from users.models    import Review, ReviewImage, User, Like, MyClass
from products.models import Product
from core.utils      import login_decorator
```

2022-05-18 06:29 UTC, lordmyshepherd requested changes

2022-05-18 06:29 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({'result' : main_category}, status=200)
```python
# 포인트는 자원(resource) 기준으로 엔드포인트 만들기!
class MainCategoriesView(View):
    def get(self, request):
        main_categories = MainCategory.objects.prefetch_related("subcategory_set")
        
        results = []

        for main_category in main_categories:
            sub_categories = [{
                "id" : sub_category.id,
                "sub_title" : sub_category.name
            } for sub_category in main_category.subcategory_set.all()]

            results.append({
                "id"             : main_category.id,
                "name"           : main_category.name,
                "sub_categories" : sub_categories
            })

        return JsonResponse({'results' : results}, status=200)
```

2022-05-18 06:29 UTC, lordmyshepherd commented on products/views.py
> +class MainView(View):
```python
class ProductsView(View):
    def get(self,request):
        # 8000/products?typeIds=[1]
        # 8000/products?typeIds=[2]
        # 8000/products?typeIds=[2]&ordering="updated_at"
        # 8000/products?typeIds=[2]&ordering="created_at"
        # 8000/products?typeIds=[2]&ordering="like_amount"

        # 8000/private/products?typeIds=[3]
        # 8000/public/products?typeIds=[3]

        type_ids = request.GET.getlist("typeIds")
        ordering = request.GET.get("ordering", "id")

        products = Product.objects.filter(type_id__in=type_ids) \
            .select_related("creator") \ 
            .annotate(like_amount=Count('product_like__id')) \
            .prefetch_related("images") \
            .order_by(ordering)

        results   = []

        for product in products:
            results.append({
            "id"              : product.id,
            "content_name"    : product.name,
            "creator_name"    : product.creator.nickname,
            "thumb_img"       : product.images.all()[0].image_urls,
            "price_amount"    : int(product.price),
            "discount_rate"   : product.discount_rate,
            "discount_coupon" : product.discount_coupon,
            "month"           : product.period,
            "like_amount"     : product.like_amount,
            "upload_date"     : str(product.created_at).replace('-','')[2:8]
        })
           
        return JsonResponse({'results' : results}, status=200)
```

2022-05-18 06:29 UTC, lordmyshepherd commented on products/views.py
> +class DetailView(View):
```suggestion
class ProductView(View):
# 상품 데이터 하나만 반화
```

2022-05-18 06:29 UTC, lordmyshepherd commented on products/views.py
> +class ListView(View):
```python
class ListView(View):
    # 위에 ProductListView와 합쳐주세요.
    #@login_decorator
    def get(self, request):
        category     = str(request.GET.get('category', '투자'))
        order_method = str(request.GET.get('sort_method', 'new'))
        limit        = int(request.GET.get('limit', 5))
        offset       = int(request.GET.get('offset', 0))

        products     = Product.objects.all()

        #user_id      = request.user.id
        result       = []
        q            = Q()

        main         = ['투자', 'Life', '프로그래밍', '음식', '지식']

        ordering_set = {
            "price"        : "price",
            "new"          : "-updated_at",
            "score"        : "-review_score",
            "like_count"   : "-like_count",
            "review_count" : "-review_count"
        }
        
        # filter 부분도 dictionary 형태로 수정해보세요.
        if category in main:
            main_id = MainCategory.objects.get(name = category).id
            q &= Q(subcategory__maincategory__name=category)
            q &= Q(subcategory__maincategory_id=main_id)

        else :
            q &= Q(subcategory__name=category)  

        products = Product.objects.filter(q).annotate(
            like_count   = Count('product_like'),
            review_count = Count('product_review')
        ).order_by(ordering_set[order_method])[offset:offset+limit]


        for product in products:
            is_liked = False
            #if Like.objects.filter(user_id = user_id, product_id = product.id).exists():
                #is_liked = True
            upload_date = str(product.created_at).replace('-','')[2:8]
            result.append({
                "id"              : product.id,
                "content_name"    : product.name,
                "creator_name"    : product.creator.nickname,
                "thumb_img"       : product.images.all()[0].image_urls,
                "upload_date"     : upload_date,
                "price_amount"    : int(product.price),
                "discount_rate"   : product.discount_rate,
                "discount_coupon" : product.discount_coupon,
                "month"           : product.period,
                "score"           : product.review_score,
                "like_amount"     : product.product_like.all().count(),
                "is_liked"        : is_liked,
                "status"          : "new"
            })
        return JsonResponse({'result' : result}, status = 200)

```

2022-05-19 04:31 UTC, NamkyuAhn commented
conflict 해결했습니다~

2022-05-19 06:33 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-05-19 06:34 UTC, merged